"""add project_member model

Revision ID: 228167267682
Revises: fb0ac1eec23f
Create Date: 2023-06-04 18:35:50.328218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228167267682'
down_revision = 'fb0ac1eec23f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('member_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['member_role_id'], ['member_role.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_member')
    op.drop_table('member_role')
    # ### end Alembic commands ###
