"""update  project_member model

Revision ID: 863eb3aa9aea
Revises: 228167267682
Create Date: 2023-06-04 19:42:03.308174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863eb3aa9aea'
down_revision = '228167267682'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'member_role', ['name'])
    op.add_column('project_member', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('project_member_creator_id_fkey', 'project_member', type_='foreignkey')
    op.create_foreign_key(None, 'project_member', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.drop_column('project_member', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_member', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_member', type_='foreignkey')
    op.create_foreign_key('project_member_creator_id_fkey', 'project_member', 'user', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_member', 'user_id')
    op.drop_constraint(None, 'member_role', type_='unique')
    # ### end Alembic commands ###
