"""update fault model_project_id

Revision ID: ae3b6a1c33ba
Revises: b14c2d58ffc1
Create Date: 2023-05-27 19:01:49.517993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3b6a1c33ba'
down_revision = 'b14c2d58ffc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fault', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fault', 'project', ['project_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fault', type_='foreignkey')
    op.drop_column('fault', 'project_id')
    # ### end Alembic commands ###
