"""Image model update

Revision ID: c2236aef1bae
Revises: 0a8b4a89b05b
Create Date: 2023-04-19 22:14:12.229086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2236aef1bae'
down_revision = '0a8b4a89b05b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
